name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch: # Allows manual triggering from GitHub UI

# Set permissions for GITHUB_TOKEN
permissions:
  contents: write
  actions: read
  checks: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build Windows Installer
      run: |
        echo "Building Windows installer..."
        npx electron-builder --win nsis --publish never
      
    - name: Build Portable Version
      run: |
        echo "Building portable version..."
        npx electron-builder --win portable --publish never
        
    - name: List final build outputs
      run: |
        echo "=== Final .exe files only ==="
        if (Test-Path "dist") {
          Get-ChildItem -Path dist -Filter "*.exe" | ForEach-Object {
            Write-Host "🎯 $($_.Name) - $([math]::Round($_.Length/1MB, 2)) MB" -ForegroundColor Green
          }
          
          echo "=== All files in dist root ==="
          Get-ChildItem -Path dist | ForEach-Object {
            if (-not $_.PSIsContainer) {
              Write-Host "$($_.Name) - $([math]::Round($_.Length/1MB, 2)) MB" -ForegroundColor Yellow
            }
          }
        } else {
          echo "❌ No dist folder found!"
        }
      shell: powershell
        
    - name: Upload Final Executables Only
      uses: actions/upload-artifact@v4
      with:
        name: timetracking-executables
        path: |
          dist/*.exe
          dist/*.yml
          dist/*.blockmap
        retention-days: 30
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*.yml
        body: |
          ## 🎉 Time Tracking App Release ${{ github.ref_name }}
          
          ### 📥 Downloads
          
          **Windows Installer (Recommended)**
          - `TimeTracking-Setup.exe` (~84 MB) - Fast startup, includes desktop shortcut and start menu entry
          
          **Portable Version**
          - `TimeTracking-Portable.exe` (~300 MB) - No installation required, can run from USB drive
          
          ### ⚡ Features
          - Global keyboard shortcuts (Ctrl+1-9)
          - Bulletproof timer that works through screen locks
          - Smart project management with soft delete
          - Weekly overview and CSV export
          - Auto-save functionality
          
          ### 🚀 Getting Started
          1. Download the installer or portable version
          2. Run the application
          3. Create your first project in the Projects tab
          4. Start tracking time with Ctrl+1-9 shortcuts!
          
          ### 📊 Data Storage
          - Database location: `Documents/TimeTracking/timetracking.db`
          - Easily portable and backup-friendly
          
          ---
          
          *Built with Electron and vibe-coded with Claude AI assistance* 🤖
        draft: false
        prerelease: false
        generate_release_notes: true
        fail_on_unmatched_files: false
        token: ${{ secrets.GITHUB_TOKEN }}